### ISSUE TITLE
Running metient without a known primary

### ISSUE THREAD

**Issue by tobyaicher** [morrislab/metient#1]
Hi,

Thanks for making this tool available the pre-print was fantastic.

I wanted to ask if you had any experience running metient in a situation where the primary site is unknown. Say I have ten samples where I am unsure which is the primary site - should I input "primary" for all samples in the site_category table? My understanding is that it would run metient ten times, each time using a different sample as a different "true primary." When metient runs (I am planning on using the evaluate mode since I have a low case number) will it compare the graph scores only within a primary designation (and output the most likely graph for each primary designation, but not comparison between primary designations), or will it compare the scores of the graphs also between different primary designations. 

I see in supplementary figure S3 for patient 1 it output three solutions, with the graph on the fair right having the primary designation "left ovary" instead of right ovary as the others do. How was metient run in this case i.e. did you input for both left and right ovary primary in the site_category_table? This case is particularly interesting because in the machina paper they argue given migration/comigration numbers the tumor likely originated from the left ovary (although room for interpretation).

Thank you again looks like a great tool!

**Comment by divyakoyy** [comment]
Hello,

Thanks for the question and the great feedback!

We do indeed have multiple patient examples in which the primary site is unknown. In this case, if you place primary in the site_category column for all these samples, Metient will detect this and automatically run multiple times - one run for each possible primary. Each run will then have multiple possible migration histories based on which sample is used as the primary for that run. We leave it up to the user on how to choose between these multiple runs, but in our paper we choose the lowest loss migration history across runs to determine the most likely primary. As you mention, this is how we determine which is the most likely primary for patients such as patient 1 from McPherson et al. in Figure S3.

Best,

Divya

**Comment by tobyaicher** [comment]
Hi,

To-follow up on this: when I place primary in the site_category column for all samples I get the following error:

`Traceback (most recent call last):
    File "/scratch/projects/evronylab/projects/Step123/pipeline/phylogenetics/Metient/evaluate_metient.py", line 44, in <module>
      met.evaluate_label_clone_tree(clone_tree_fn, ref_var_fn, weights, print_config,
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/metient.py", line 56, in evaluate_label_clone_tree
      return mig_hist.evaluate_label_clone_tree(tree_fn, tsv_fn, weights, print_config, output_dir, run_name, O=O, batch_size=batch_size, 
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/lib/migration_history_inference.py", line 164, in evaluate_label_clone_tree
      return evaluate(tree_fn, tsv_fn, weights, print_config, output_dir, run_name,
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/lib/migration_history_inference.py", line 170, in evaluate
      Ts, pooled_tsv_fns = prep_inputs([tree_fn], [tsv_fn], [run_name], estimate_observed_clones, output_dir)
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/lib/migration_history_inference.py", line 154, in prep_inputs
      dutil.validate_prepooled_tsv(tsv_fn)
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/util/data_extraction_util.py", line 81, in validate_prepooled_tsv
      validate_unpooled_or_pooled_df(df, tsv_fn, index_cols)
    File "/home/tpa239/evronylab/projects/Step123/pipeline/phylogenetics/Metient/met/lib/python3.8/site-packages/metient/util/data_extraction_util.py", line 54, in validate_unpooled_or_pooled_df
      assert(set(df['site_category'])==set(['primary', 'metastasis']))
  AssertionError`

I think the issue is this line of code here:
https://github.com/morrislab/metient/blob/82cd6a051641923cf77aad047528ff898f45fc1d/metient/util/data_extraction_util.py#L54

where there is an assertion error that requires both primary and metastasis in the site_category column. I ran with python -O and it worked i.e. output multiple solutions with each sample as a primary.

I wanted to let you know in case you wanted to give users the option to input all sample as primary samples without having to over-ride assertion errors.

Toby

**Comment by divyakoyy** [comment]
I didn't consider that use case, but there's no reason to disallow it. Thanks for following up, will make sure this assertion is not as stringent!

**Comment by tobyaicher** [comment]
Thank you!!!
